version = 1

[update]
always = true # default: false

[approve]
auto_approve_usernames = ["ImgBotApp", "imgbot"]

[merge.automerge_dependencies]
versions = ["minor", "patch"]
usernames = ["dependabot"]

# https://kodiakhq.com/docs/recipes#better-merge-messages
[merge.message]
title = "pull_request_title" # default: "github_default"
body = "pull_request_body" # default: "github_default"
include_pr_number = true
include_coauthors = true
